### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by eduardo626** [dappsnation/ng-rive#17]
Greetings, I am implementing Rive for animations in an angular app and I get the following error, I already followed the documentation and exported my animation for version 6, but I always get this error.

![Captura](https://user-images.githubusercontent.com/45045262/118050069-e7e63c00-b33b-11eb-912c-96161d28b481.PNG)

**Comment by Rejomeee** [comment]
I got the same error. how can we fix this.

**Comment by GrandSchtroumpf** [comment]
Hello @eduardo626,
I've released version 0.1.0 which support the new version of rive-canvas and rive files. Could give it a try and let me know how it goes: 
```typescript
npm install ng-rive@latest
```

**Comment by eduardo626** [comment]
I tried the changes but it still does not work, now it has the following errors.

![Captura](https://user-images.githubusercontent.com/45045262/118689544-5b68cd00-b7c4-11eb-86af-9e564df4e501.PNG)
![Captura2](https://user-images.githubusercontent.com/45045262/118689546-5b68cd00-b7c4-11eb-8f65-977334ab4366.PNG)

**Comment by GrandSchtroumpf** [comment]
hmmm looks like an Ivy error. Are you using Ivy ? Since version 12, the View Engine has been deprecated, and it's recommended for angular library developer to publish the lib compiled with Ivy ([see article](https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4)).

If you're already using Ivy, can you print the output of `ng version` ?
Also you can also try to do : 
```
npm uninstall ng-rive rive-canvas
npm install ng-rive@latest
```

**Comment by eduardo626** [comment]
I tried a new project and I get the same error
![Captura3](https://user-images.githubusercontent.com/45045262/118698225-6116e080-b7cd-11eb-85b2-64b3bc6e7702.PNG)

**Comment by GrandSchtroumpf** [comment]
I'm sorry about that... Could you setup a stackblitz or a repo that I can clone to debug your issue ?

**Comment by eduardo626** [comment]
I managed to fix the problem by updating Angular to version 12

**Comment by GrandSchtroumpf** [comment]
Ok thanks for the feedback.
As this library is very new and the current version of angular is 12, I would rather not try to support previous version.
Please let me know if it is a big issue for you, in this case I'll debug it and apply a fix.
