### ISSUE TITLE
Rendering multiple rive assets together causes "BindingError" and One Shot animation doesn't reset properly

### ISSUE THREAD

**Issue by Aashu-Dubey** [dappsnation/ng-rive#30]
Hi, first of all thanks for the package, I recently used this extensively in a demo [Ionic + Angular app](https://github.com/Aashu-Dubey/Ionic-UI-Templates/tree/main/ionic_ui_templates/src/app/templates/course-rive), you can see the demo for that [here](https://twitter.com/aashudubey_ad/status/1617186151860948992), overall the package works just fine, but there were some issues I faced, which I'm detailing below.

### 1. Loading multiple rive assets together causes "BindingError"
The app uses many rive assets in a single screen, which as they are all rendered together cause many to fail and only few are successfully rendered, as you can see below.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/46301285/214667562-5c066db4-7cea-49bc-9000-e2be227ca6d6.png">

for others, the package throws `"BindingError: Expected null or instance of StateMachine, got an instance of Animation"`

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/46301285/214668060-b511bc19-3e8b-4c8d-98c0-5bcc9bc0a06a.png">

Though luckily, I was able to find a workaround for this, the trick was to load them all with some delay, as you can see [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/navigation/side-menu/side-menu.component.ts#L41-L51)

<img width="515" alt="image" src="https://user-images.githubusercontent.com/46301285/214669489-020c93f8-8c39-4e20-88c2-c09248d866df.png">

and only render after value is true, like [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/navigation/side-menu/menu-row/menu-row.component.html#L15)

<img width="556" alt="image" src="https://user-images.githubusercontent.com/46301285/214670035-bb36fad3-889e-4c46-958c-c7af5f7e8272.png">

So this fixed the issue, only that this workaround is needed to be applied on almost every rive asset used on the page like [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/navigation/bottom-tab-bar/bottom-tab-bar.component.ts#L17-L21) and [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/views/on-boarding/on-boarding.page.ts#L32-L35) and few more.

Though this particular issue is also reported on #26.

### 2 One Shot animations keeps on repeating
It's better to explain it through a video.
it's just a simple button, with mode `one-shot` and `autoreset` true, the code for this can be found [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/views/on-boarding/on-boarding.page.html#L34-L42), as you can see in the video it doesn't reset properly, sometimes it plays for once, sometimes for 2, 4, 7, 8 etc. times.
Maybe I didn't use this asset properly, so feel free to correct me. The detail about the button asset can be found [here](https://designcode.io/swiftui-rive-button-animation).

https://user-images.githubusercontent.com/46301285/214675978-b42f6175-2a75-4a37-b8a5-f0e381c14358.mp4

---
These 2 were the main issues that I encountered, let me know if more info is needed.

This demo can also be used as a good case study for possible improvements.

Thanks!

**Comment by GrandSchtroumpf** [comment]
Hello, sorry for the delay, I've been quite busy recently, I'll take a look at this issue in the upcoming days.

**Comment by GrandSchtroumpf** [comment]
Hello, first of all thanks for the detailed issue.
- Concerning the first error, I think version 0.2.0 should fix it, it was an issue with how the `ng-rive` was keeping the files in memory.
- Concerning the second error, since version 0.2.1 the input `mode` from the player has been deprecated. It was used as a patch before State Machine. As State Machine are now very stable, I would definitely recommend using Trigger input instead.

**Comment by Aashu-Dubey** [comment]
Hi, thanks for looking into this.

I tried v0.2.1, but unfortunately the issues are still there

1. After installing latest version I removed all the workarounds as mentioned in the issue, but I'm still getting similar behaviour with same error message.
See the attached video using latest version

https://user-images.githubusercontent.com/46301285/218272623-c1f0580d-a25b-4a1a-b67a-bb21d97186cc.mp4

But of course, after I open the screen again, all of them are being rendered successfully.

2. first thing after update, as `mode` and `autoreset` are removed, button animation is not working anymore, but I'm also not able to make it work by using trigger input as suggested by you, below are the changes I made, let me know how it should be done.
I used both the `#trigger` and `[value]` approach on `riv-input`, but none of them are working

<img width="754" alt="image" src="https://user-images.githubusercontent.com/46301285/218273046-50c80f65-2554-48a3-9e30-0fb70b56b82a.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/46301285/218273116-289dd80e-c07f-4900-9e85-6253fb9eee33.png">

https://user-images.githubusercontent.com/46301285/218273457-0c25869b-fd55-499a-9f0f-e7b5c57e2c4e.mp4

---
So I don't think any of the original mentioned issues are fixed with the update, but of course as [the project](https://github.com/Aashu-Dubey/Ionic-UI-Templates/tree/main/ionic_ui_templates/src/app/templates/course-rive) is open source, you can give it a try yourself to better understand and fix the issue.

**Comment by GrandSchtroumpf** [comment]
Hello, sorry it didn't fix your issues, I'll dig more into it, and come back to you when I figure out what's going on.
Could you point me out to your riv files in your repo so I can try them in the playground of `ng-rive` ?

**Comment by Aashu-Dubey** [comment]
Sure, you can find them [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/tree/main/ionic_ui_templates/src/assets/course_rive/rive).

**Comment by GrandSchtroumpf** [comment]
Concerning the icons I've published a new version that should fix your issue: 0.2.2
Concerning the button I've uploaded it into the rive editor, and it seems that the state machine was not created. I've updated the file with this configuration and it works on the playground:
![image](https://user-images.githubusercontent.com/8143464/218308422-44213a8d-52a8-4d88-ab09-d9105c0f52b9.png)

I've created a working example with your riv files here 
https://github.com/dappsnation/ng-rive/blob/master/apps/playground/src/app/artboard/artboard.component.html

Let me know if you still have the issues

**Comment by Aashu-Dubey** [comment]
Thanks for the quick update, I gave v0.2.2 a try, but unfortunately the issue seems to be still the same.

1. Behaviour is still pretty much same, see the video using v0.2.2

https://user-images.githubusercontent.com/46301285/218972477-fc3c49c4-3edf-40c6-970a-93fdc29f2482.mp4

This is the code for the bottom tab icons, I'm using, which I'm sure is pretty much same as the working example you shared
<img width="579" alt="image" src="https://user-images.githubusercontent.com/46301285/218965803-6cf5a9c8-fd66-4f60-a6d0-81fccf3be223.png">

again, if I re-enter screen all the icons are rendering properly, this error is only first time.

2. First of all, It's great that it's working after some changes in the file, but I wanna ask, as I created same example using Flutter [available here](https://github.com/Aashu-Dubey/flutter-samples/tree/main/lib/rive_app) and there's also a SwiftUI version following [this course](https://designcode.io/swiftui-rive-animated-app), and both of them are using same button.riv file, and working just fine, so why do we need to change that in case for Angular ng-rive?
Is there a difference in the way their runtime and this one handle this?
You can also check the code for them to see the code side of things to render & control the button.

and for the below code for button.riv __**(without your changes)**__, till version 0.2.1 it was rendering the button, but after updating to v0.2.2 it's not
<img width="775" alt="image" src="https://user-images.githubusercontent.com/46301285/218966610-aa94bf82-0025-422e-8d97-c1caeb41f9bd.png">

| v0.2.1 | v0.2.2 |
| --- | --- |
| <img width="255" alt="image" src="https://user-images.githubusercontent.com/46301285/218965447-98526247-c693-41d2-af67-e442f4ddc6e9.png"> | <img width="198" alt="image" src="https://user-images.githubusercontent.com/46301285/218966945-39bdf663-9ac6-4721-9960-4a77ce182cfd.png"> |

I don't know what changed but it's throwing this error now
<img width="827" alt="image" src="https://user-images.githubusercontent.com/46301285/218968575-70f522aa-f9e7-497e-9021-15529fe6094c.png">

So till 0.2.1, the issue was only to control the button, render was fine, but now it's not even rendering.

---

Can you please try the ionic project that I shared for this example? I'm pretty sure all the issues I'm mentioning would be easily reproducible.

**Comment by GrandSchtroumpf** [comment]
Concerning the "Expected null or an instance of state machine" I'm not sure why this happens, I can investigate, but I don't have much time these days unfortunately. If you've got some idea, it would greatly help. You can also do a PR if you want.

Concerning the "State Machine 1" error, it comes from [here](https://github.com/dappsnation/ng-rive/blob/master/libs/ng-rive/src/lib/state-machine.ts#L35). In your case it means that your artboard doesn't hae any state machine. As I pointed out in my comment [above](https://github.com/dappsnation/ng-rive/issues/30#issuecomment-1427008610), you button animation file had no state machine. I created one for your file and tested it with the code below and it worked. 
```html
<button (click)="run.fire()">
  <canvas riv="button" width="236" height="64" artboard="main">
    <riv-state-machine name="activation" play>
      <riv-input name="run" #run="rivInput"></riv-input>
    </riv-state-machine>
  </canvas>
</button>
```
You can find the file [here](https://github.com/dappsnation/ng-rive/blob/master/apps/playground/src/assets/rive/button.riv) if you want to try.

**Comment by GrandSchtroumpf** [comment]
I cloned your repo, installed ng-rive@0.2.2 and ran `npm run start` and the bottom bar is working fine locally.
I tried on Edge (chromium) & Firefox with no issues.
Can you create a minimal stackblitz example ? It would be easier to debug

**Comment by Aashu-Dubey** [comment]
> Concerning the "Expected null or an instance of state machine" I'm not sure why this happens, I can investigate, but I don't have much time these days unfortunately. If you've got some idea, it would greatly help. You can also do a PR if you want.

I can totally understand, take your time, as I said the workaround mentioned in the main issue is working fine, and this is a example project, so not that critical to me.
I'm just trying my best to provide you all the details that can be helpful to fix the issue, unfortunately I currently don't have much free time either, but will see if I can look into this.

> Concerning the "State Machine 1" error, it comes from [here](https://github.com/dappsnation/ng-rive/blob/master/libs/ng-rive/src/lib/state-machine.ts#L35). In your case it means that your artboard doesn't hae any state machine. As I pointed out in my comment [above](https://github.com/dappsnation/ng-rive/issues/30#issuecomment-1427008610), you button animation file had no state machine. I created one for your file and tested it with the code below and it worked.

That's fine, and I can also use the updated file you provided to make it work, my only question regarding this is that the same file is used for same project in 3 different tech [SwiftUI](https://designcode.io/swiftui-rive-animated-app), [Flutter](https://github.com/Aashu-Dubey/flutter-samples/tree/main/lib/rive_app) and there's another version in [react-native](https://github.com/lklima/rive-animated-app), and it's working there, so why we need to make some changes in case of Angular and is there difference between their rive runtime and this one?
And again, even here the initial problem was just button performing animation multiple times instead of just once, other than this issue I was able to render and animate the button just fine (using `riv-player`), so I don't think not having state machine was main issue here (or it was after you removed the `riv-player` approach in newer versions).

> I cloned your repo, installed ng-rive@0.2.2 and ran npm run start and the bottom bar is working fine locally.
I tried on Edge (chromium) & Firefox with no issues.

It is supposed to work fine as I've added workaround as mentioned, did you remove them before testing, like [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/navigation/bottom-tab-bar/bottom-tab-bar.component.ts#L19-L21), [here](https://github.com/Aashu-Dubey/Ionic-UI-Templates/blob/main/ionic_ui_templates/src/app/templates/course-rive/navigation/side-menu/side-menu.component.ts#L43-L51), or any file where rive is used (more details in the main issue).

**Comment by GrandSchtroumpf** [comment]
I don't really know how the other runtime are working, but currently there is no way for me to know if a LinearAnimation is a "one-shot", a "loop" or a "ping-pong". In the case of "one-shot" we would want to set the `play` state to `false` when the animation has ended, and reset the time to 0 (which is not the case for loop & ping-pong). Also if you set `speed` to `-1` you need to reverse this process ^^. So the `riv-player` has to manage a lot of things just to support `one-shot` cases (for "loop" & "ping-pong" it's just a matter of `play = true/false`).

With the StateMachine's input we don't need to support this workaround anymore, this is the way Rive expects use to manage animations. That's why I'm deprecating the `mode` input of the `riv-player` in favor of StateMachine.

I did remove the setTimeout, and update `show: true` on every menu item, and it's still working fine with `ng-rive@0.2.2` on firefox & Edge (I didn't try the emulators).
It might be a caching issue with the rive.wasm file if you've got a service worker... or an issue with the emulator (just trying some random guesses here).

**Comment by GrandSchtroumpf** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.
